core/urls.py
from django.urls import path,re_path
from .views import homeview,itemdetailview,add_to_cart,remove_from_cart,OrderSummaryView,remove_single_item_from_cart,CheckoutView,PaymentView,search_results,productview,paintingsview,photographsview,prints,profile,artists,CreateDetail,sculptures,myprofile,ItemList,ArtistList,ItemDetail,UserList,UserDetail,MessageView,CreateShow,UpdateDetail,ItemDelete,UpdateShow,ShowDelete,Account,SummaryView,blog,BlogDetail,UpdateBlog,DeleteBlog
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'core'


urlpatterns = [
    path('',homeview.as_view(),name = 'home'),
    path('artists/',artists.as_view(),name = 'artists'),
    path('items',productview,name = 'items'),
    path('checkout/',CheckoutView.as_view(),name = 'checkout'),
    path('paintings/',paintingsview,name = 'paintings'),
    path('prints/',prints,name = 'prints'),
    path('profile/<int:pk>/',profile.as_view(),name = 'profile'),
    path('photographs/',photographsview,name = 'phtotographs'),
    path('myprofile/',myprofile.as_view(),name = 'myprofile'),
    path('sculptures/',sculptures,name = 'sculptures'),
    path('order-summary/',OrderSummaryView.as_view(),name = 'order-summary'),
    path('product/<slug>/',itemdetailview.as_view(),name = 'product'),
    path('add-to-cart/<slug>/',add_to_cart,name = 'add-to-cart'),
    path('remove-from-cart/<slug>/',remove_from_cart,name = 'remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/',remove_single_item_from_cart,name = 'remove-single-item-from-cart'),
    path('payment/<payment_option>/',PaymentView.as_view(),name = 'payment'),
    path('search/',views.search_results, name='search_results'),
    path('upload/', CreateDetail.as_view(), name = 'upload'),
    path('show/', CreateShow.as_view(), name = 'show'),
    path('api-item/', ItemList.as_view(), name = 'api-item'),
    path('api-item/<int:pk>/', views.ItemDetail.as_view()),
    path('api-user/', UserList.as_view(), name = 'api-user'),
    path('api-user/<int:pk>/', views.UserDetail.as_view()),
    path('api-artist/', ArtistList.as_view(), name = 'api-artist'),
    path('like/', views.like , name= 'like'),
    path('message/', MessageView.as_view() , name= 'message'),
    path('product/<slug>/update', UpdateDetail.as_view(), name = 'product-update'),
    path('product/<slug>/delete',ItemDelete.as_view(), name = 'product-delete'),
    path('<int:pk>/update', UpdateShow.as_view(), name = 'show-update'),
    path('<int:pk>/delete', ShowDelete.as_view(), name = 'show-delete'),
    path('seller-account/',Account.as_view() , name= 'seller-account'),
    path('summary-view/',SummaryView.as_view() , name= 'summary-view'),
    path('blog/',blog.as_view() , name= 'blog'),
    path('blog/<int:pk>/', BlogDetail.as_view(), name = 'blog-detail'),
    path('blog/<int:pk>/update', UpdateBlog.as_view(), name = 'update-blog'),
    path('blog/<int:pk>/delete', DeleteBlog.as_view(), name = 'delete-blog'),
    path('searches/',views.search_result, name='search_result'),
    

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls',namespace = 'core')),
    path('social-auth/',include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

django-allauth-master/allauth/account/urls.py
from django.urls import path, re_path

from . import views


urlpatterns = [
    path("signup/", views.signup, name="account_signup"),
    path("login/", views.login, name="account_login"),
    path("logout/", views.logout, name="account_logout"),
    path("password/change/", views.password_change,
         name="account_change_password"),
    path("password/set/", views.password_set, name="account_set_password"),
    path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", views.email, name="account_email"),
    path("confirm-email/", views.email_verification_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$", views.confirm_email,
            name="account_confirm_email"),

    # password reset
    path("password/reset/", views.password_reset,
         name="account_reset_password"),
    path("password/reset/done/", views.password_reset_done,
         name="account_reset_password_done"),
    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            views.password_reset_from_key,
            name="account_reset_password_from_key"),
    path("password/reset/key/done/", views.password_reset_from_key_done,
         name="account_reset_password_from_key_done"),
]

django-allauth-master/example/example/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic.base import TemplateView

admin.autodiscover()

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/',
         TemplateView.as_view(template_name='profile.html')),
    path('admin/', admin.site.urls),
]

templates/base.html
{% load static %}
{% load cart_template_tags%}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel="shortcut icon" href="{% static 'logos.png'%}" type="image/4x-icon">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
    
  <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{%static 'css/style.min.css'%}" rel="stylesheet">
  <link href="{%static 'css/style.css'%}" rel="stylesheet">
  <link href="{%static 'css/styles2.css'%}" rel="stylesheet">
 
  <link href="{%static 'css/navbar.css'%}" rel="stylesheet">
  <link href="{%static 'css/artist.css'%}" rel="stylesheet">
  <link href="{%static 'css/home.css'%}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet">
  <style type="text/css">
       html,
    body,
   
    .carousel {
     
      font-family: 'Spectral', serif;
      scroll-behavior: smooth;
      
   
    }
  </style>
</head>



<body >

    <!-- <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div> -->
    <header class="header-section" style="text-align: center;align-items: center;" > 
      <div class="header-top">
        <div class="main-container">
          <div class="row" >
            <div class="col-lg-2 " id = "images">
              <!-- logo -->
              <a href="/">
                <img src="{% static 'logos.png'%}" alt="" srcset="" style="height: 140px;width: 140px;" class="images">
              </a>
             
            </div>
            <div class="col-xl-6 col-lg-5" style="align-items: center;margin-top: 15px;"  >
              <form class="header-search-form" role="search" action="{% url 'core:search_results' %}" style="width: 70%;margin-left: auto;">
                <input type="text" placeholder="Search product ...." name="title" style="border: 1px solid black;border-radius: 0;background-color: transparent;">
                <button><i class="fas fa-search"></i></button>
              </form>
            </div>
            <div class="col-xl-4 col-lg-5 " style="margin-top: 20px;"  >
              <div class="user-panel" >
                <div class="up-item dropdown">
                  
                 <span style="font-size: 15px;display: inline-flexbox;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class=" dropdown-toggle" >  <i class="far fa-user" > </i> Account</span>
                  
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" >
                    {% if user.is_authenticated %}
                  <a class="dropdown-item"  href="{% url 'account_logout'%}">Logout</a>
                  <a href="/myprofile" class="dropdown-item" > Account </a>
                  <a href="/myprofile" class="dropdown-item" > Favourites </a>
                  <a href="/myprofile" class="dropdown-item" > Orders </a>
                  <a href="/message" class="dropdown-item" > Messages</a>
               
                  {% else %}
                  <a  class="dropdown-item" href="{% url 'account_login'%}">Sign In</a>  
                  
                  <a class="dropdown-item"  href="{% url 'account_signup'%}">Create Account</a>
                  {%endif%}
                </div>
                </div>
                <div class="up-item">
                  <div class="shopping-card">
                    <a href="{%url 'core:order-summary'%}">
                      <i class="fas fa-shopping-bag"></i>
                  
                    
                    <span style="font-weight: 500;">{{request.user|cart_item_count}} </span>
                  </div>
                 Shopping Cart</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <nav class="main-navbar"  >
        <div class="container">
          <!-- menu -->
          <ul class="main-menu"  >
          
            <li style="margin-right: 12px;"><a href="/paintings">PAINTINSGS</a></li>
            <li style="margin-right: 12px;"><a href="/photographs">PHOTOGRAPHS</a></li>
            <li style="margin-right: 12px;"><a href="/prints">PRINTS</a></li>
            <li style="margin-right: 12px;"><a href="/sculptures">SCULPTUTES</a></li>
            <li><a href="/artists">ARTISTS</a></li>
            
            
         
          </ul>
        </div>
      </nav>
    </header>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
    <section class="footer-section">
      <div class="container-fluid">
      
        <div class="row">
    
          <div class="col-lg-3 col-sm-6">
            <div class="footer-widget about-widget">
              <a href="https://hooliganlivefree.com"><img src="{% static 'logo.png'%}" alt="" style="margin-left: 20px;height: 70%; width: 70%;"></a>
            </div>
          </div>
          <div class="col-lg-3 col-sm-6">
            <div class="footer-widget about-widget">
              <h2>About Us</h2>
              <p >Welcome to Hooligan LLC, We <br> represent artists from all over  the <br>  world find amazing photographs, <br>paintings,sculptures and prints.</p>
              <img src="{% static 'cards.png' %}" alt="" style="height: 50%;width: 50%;">
            </div>
          </div>
          
          <div class="col-lg-3 col-sm-6">
            <div class="footer-widget about-widget">
              <h2>DON'T GET LOST</h2>
              <ul>
                <ul>
                  <li><a href="/">Home</a></li>
                  <li><a href="/photographs">Photographs</a></li>
                  <li><a href="/artists">Artists</a></li>
                  <li><a href="/paintings">Paintings</a></li>
                  <li><a href="/sculptures">Sculptures</a></li>
                  <li><a href="{%url 'core:order-summary'%}">Order Summary</a></li>
                  <li><a href="/blog">Blog</a></li>
                </ul>
              
              </ul>
              
            </div>
          </div>
        
          <div class="col-lg-3 col-sm-6">
            <div class="footer-widget contact-widget">
              <h2>Contact Info</h2>
              <div class="con-info">
              
                <p> <i class="fas fa-home" style="margin-right: 10px;"></i>Hooligan LLC </p>
              </div>
              <div class="con-info">
                
                <p> <i class="fas fa-map-marker-alt" style="margin-right: 10px;"></i>New York,USA </p>
              </div>
        
            </div>
          </div>
        </div>
      </div>
      <div class="social-links-warp">
        <div class="container">
          <div class="social-links" style="text-align: center;">
            <a href="https://www.instagram.com/hooliganlivefree/?hl=en" class="instagram"><i class="fab fa-instagram"></i><span>instagram</span></a>
        
            <a href="https://www.facebook.com/HooliganLLC/" class="facebook"><i class="fab fa-facebook"></i><span>facebook</span></a>
            <a href="https://twitter.com/HooliganLLC" class="twitter"><i class="fab fa-twitter"></i><span>twitter</span></a>
          
          </div>
    
    
    
        </div>
      </div>
    </section>
    
    
    
    
    
    
    
    <a href="#" class="back-to-top"><i class="fas fa-chevron-up"></i></a>

    <script type="text/javascript">
      $(window).scroll(function() {
    if ($(this).scrollTop() > 100) {
      $('.back-to-top').fadeIn('slow');
    } else {
      $('.back-to-top').fadeOut('slow');
    }
  })
  var myButton = $('#stripeBtn');  // your button ID here
    myButton.on('click', function(){
        myButton.prop('disabled', true);
    });
  
    new WOW().init();

  </script>
</body>
</html>

templates/order_summary.html
{% load static %}
{% load cart_template_tags%}


{% block content %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Dagallery-cart</title>
  <link rel="shortcut icon" href="{% static 'logos.png'%}" type="image/4x-icon">
  <!-- Font Awesome -->
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,300i,400,400i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{%static 'css/style.min.css'%}" rel="stylesheet">
  <link href="{%static 'css/style.css'%}" rel="stylesheet">
  <link href="{%static 'css/hero.css'%}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet">
 
  <link href="{%static 'css/navbar.css'%}" rel="stylesheet">
  <link href="{%static 'css/home.css'%}" rel="stylesheet">
  <link href="{%static 'css/order.css'%}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,200;0,300;1,200&display=swap" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      
      font-family: 'Spectral', sans-serif;
      
      scroll-behavior: smooth;
    }
  



  </style>
</head>

<body>
  <header class="header-section" style="text-align: center;align-items: center;" > 
    <div class="header-top">
      <div class="main-container">
        <div class="row" >
          <div class="col-lg-2 " id = "images">
            <!-- logo -->
            <a href="/">
              <img src="{% static 'logos.png'%}" alt="" srcset="" style="height: 140px;width: 140px;" class="images">
            </a>
           
          </div>
          <div class="col-xl-6 col-lg-5" style="align-items: center;margin-top: 15px;"  >
            <form class="header-search-form" role="search" action="{% url 'core:search_results' %}" style="width: 70%;margin-left: auto;">
              <input type="text" placeholder="Search product ...." name="title" style="border: 1px solid black;border-radius: 0;background-color: transparent;">
              <button><i class="fas fa-search"></i></button>
            </form>
          </div>
          <div class="col-xl-4 col-lg-5 " style="margin-top: 20px;"  >
            <div class="user-panel" >
              <div class="up-item dropdown">
                
               <span style="font-size: 15px;display: inline-flexbox;" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class=" dropdown-toggle" >  <i class="far fa-user" > </i> Account</span>
                
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  {% if user.is_authenticated %}
                  <a class="dropdown-item"  href="{% url 'account_logout'%}">Logout</a>
              <a href="/myprofile" class="dropdown-item" > Account </a>
              <a href="/myprofile" class="dropdown-item" > Favourites </a>
              <a href="/myprofile" class="dropdown-item" > Orders </a>
              <a href="/message" class="dropdown-item" > Messages</a>>
  
             
                {% else %}
                <a  class="dropdown-item" href="{% url 'account_login'%}">Sign In</a>  
                
                <a class="dropdown-item"  href="{% url 'account_signup'%}">Create Account</a>
                {%endif%}
              </div>
              </div>
              <div class="up-item">
                <div class="shopping-card">
                  <a href="{%url 'core:order-summary'%}">
                    <i class="fas fa-shopping-bag"></i>
                
                  
                  <span style="font-weight: 500;">{{request.user|cart_item_count}} </span>
                </div>
               Shopping Cart</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <nav class="main-navbar"  >
      <div class="container">
        <!-- menu -->
        <ul class="main-menu"  >
        
          <li style="margin-right: 12px;"><a href="/paintings">PAINTINSGS</a></li>
          <li style="margin-right: 12px;"><a href="/photographs">PHOTOGRAPHS</a></li>
          <li style="margin-right: 12px;"><a href="/prints">PRINTS</a></li>
          <li style="margin-right: 12px;"><a href="/sculptures">SCULPTUTES</a></li>
          <li><a href="/artists">ARTISTS</a></li>
          
          
       
        </ul>
      </div>
    </nav>
  </header>
  <div class="card" style="background-color: white;margin-top: 30px; margin-bottom: 30px;">
    <div class="row">
        <div class="col-md-8 cart">
            <div class="title">
                <div class="row">
                    <div class="col">
                        <h4><b>Shopping Cart</b></h4>
                    </div>
                    <div class="col align-self-center text-right text-muted">{{request.user|cart_item_count}} Item(s)</div>
                </div>
            </div>
            {% for order_item in object.items.all %}
            <div class="row border-top border-bottom">
             
                <div class="row main align-items-center">
                <div class="col-2"><img class="img-fluid" src="{{order_item.item.image.url}}"></div>
                    <div class="col">
                     
                        <div class="row">{{order_item.item.title}}</div>
                    </div>
                    <div class="col"> <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">-</a><a href="#" class="border">{{order_item.quantity}}</a><a href="{% url 'core:add-to-cart' order_item.item.slug %}">+</a> </div>
                  
                    <div class="col">&dollar;  {% if order_item.item.discount_price %}{{order_item.get_amount_saved}}
                    <span class="badge badge-primary"> saved ${{order_item.get_total_discount_item_price}} </span> 
          
                      {% else %}
                      
                      {{order_item.get_total_item_price}}
                    
                      {%endif%} </div>
                      <div class="col"><a href="{% url 'core:remove-from-cart' order_item.item.slug%}"><i class="fas fa-trash float-left"  style="color: red;"></i></a></div>
                  </div>
            </div>
            
            
            {%empty%}
            <h1>Oops Your Cart is empty</h1>
            
            {%endfor%}
            <div class="back-to-shop"><a href="/">&leftarrow;Back to shop  <img src="{% static 'cart.png'%}" alt="" srcset="" style="height: 30px; width: 30px;"></span></a><span ></div>
            </div>
        {% if object.get_total %}
        <div class="col-md-4 summary">
            <div>
              
                <h5><b>Summary</b></h5>
            </div>
          
            <div class="row">
                 
               
               
            </div>
            <!-- <form>
                <p>SHIPPING</p> <select>
                    <option class="text-muted">Standard-Delivery- &dollar;15.00</option>
                </select>
                <p>GIVE CODE</p> <input id="code" placeholder="Enter your code">
            </form> -->
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                <div class="col">TOTAL PRICE</div>
                <div class="col text-right">&dollar; {{object.get_total}}</div>
            </div>  <a href="/checkout"><button class="btn">CHECKOUT</button></a>
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
            <div class="col">
            <img src="{% static 'logos.png'%}" alt="" srcset="" style="width: 100%; height: 100%;">
            
          </div>
          <div class="col text-right"  style="margin-top: 30px;">
            Thank you for Shopping with us
          </div>
        </div>
        </div>
        <div>
          
        </div>
        {%endif%}
    </div>
</div>

<section class="footer-section">
  <div class="container-fluid">
  
    <div class="row">

      <div class="col-lg-3 col-sm-6">
        <div class="footer-widget about-widget">
         
          <a href="https://hooliganlivefree.com" target="_blank"><img src="{% static 'logo.png'%}" alt="" style="margin-left: 20px;height: 70%; width: 70%;"></a>
        </div>
      </div>
      <div class="col-lg-3 col-sm-6">
        <div class="footer-widget about-widget">
          <h2>About Us</h2>
          <p >Welcome to Hooligan LLC, We <br> represent artists from all over  the <br>  world find amazing photographs, <br>paintings,sculptures and prints.</p>
          <img src="{% static 'cards.png' %}" alt="" style="height: 50%;width: 50%;">
        </div>
      </div>
      
      <div class="col-lg-3 col-sm-6">
        <div class="footer-widget about-widget">
          <h2>DON'T GET LOST</h2>
          <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/photographs">Photographs</a></li>
            
            <li><a href="/paintings">Paintings</a></li>
            <li><a href="/sculptures">Sculptures</a></li>
            <li><a href="{%url 'core:order-summary'%}">Order Summary</a></li>
            <li><a href="/blog">Blog</a></li>
          
          </ul>
          
        </div>
      </div>
    
      <div class="col-lg-3 col-sm-6">
        <div class="footer-widget contact-widget">
          <h2>Contact Info</h2>
          <div class="con-info">
          
            <p> <i class="fas fa-home" style="margin-right: 10px;"></i>Hooligan LLC </p>
          </div>
          <div class="con-info">
            
            <p> <i class="fas fa-map-marker-alt" style="margin-right: 10px;"></i>New York,USA </p>
          </div>
    
      </div>
    </div>
  </div>
  <div class="social-links-warp">
    <div class="container">
      <div class="social-links" style="text-align: center;">
        <a href="https://www.instagram.com/hooliganlivefree/?hl=en" class="instagram"><i class="fab fa-instagram"></i><span>instagram</span></a>
        
        <a href="https://www.facebook.com/HooliganLLC/" class="facebook"><i class="fab fa-facebook-f"></i><span>facebook</span></a>
        <a href="https://twitter.com/HooliganLLC" class="twitter"><i class="fab fa-twitter"></i><span>twitter</span></a>
      
      
      </div>



    </div>
  </div>
</section>







<a href="#" class="back-to-top"><i class="fas fa-chevron-up"></i></a>



<script src="/static_files/js/jquery.slicknav.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.3/TweenMax.min.js"></script>
<script type="text/javascript" src="{%static 'js/jquery-3.4.1.min.js'%}"></script>
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js'%}"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/SlickNav/1.0.10/jquery.slicknav.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

<script src="{% static 'js/scripts.js' %}"></script>
  <script type="text/javascript">
      $(window).scroll(function() {
    if ($(this).scrollTop() > 100) {
      $('.back-to-top').fadeIn('slow');
    } else {
      $('.back-to-top').fadeOut('slow');
    }
  });
    new WOW().init();

  </script>
</body>

</html>
{% endblock content %}

templates/scripts.html
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scripts.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>